services:

  mongodb:
    image: mongo:8
    container_name: three-tier-mongodb
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: CHANGE_ME

    volumes:
      - mongodb-data:/data/db

    networks:
      - three-tier-network


  backend:
    image: three-tier-backend:latest
    container_name: three-tier-backend
    restart: unless-stopped

    environment:
      PORT: 3500
      MONGO_USERNAME: admin
      MONGO_PASSWORD: CHANGE_ME
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: todoapp

    depends_on:
      - mongodb

    networks:
      - three-tier-network


  frontend:
    image: three-tier-frontend:latest
    container_name: three-tier-frontend
    restart: unless-stopped

    ports:
      - "3000:80"

    depends_on:
      - backend

    networks:
      - three-tier-network


volumes:
  mongodb-data:


networks:
  three-tier-network:
