apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: three-tier-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3500
          env:
            - name: PORT
              value: "3500"
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
            - name: MONGO_HOST
              value: "mongodb"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DATABASE
              value: "todoapp"

---

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 3500
      targetPort: 3500
